- name: Configure Let's Encrypt
  hosts: balancer
  become: true
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - name: Install certbot package
      package:
        name: certbot
        state: present

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started

    - name: Obtain SSL certificate
      shell: >
        certbot certonly --non-interactive --agree-tos
        --nginx
        --email ekaterina_atrucks@atrucks.su
        -d "{{ letsencrypt_domain }}"
      args:
        creates: "/etc/letsencrypt/live/{{ letsencrypt_domain }}/fullchain.pem"
