- name: Ensure certbot is installed
  package:
    name: certbot
    state: present
- name: Ensure certbot is executable
  command: chmod +x /usr/bin/certbot-auto
  args:
    creates: /usr/bin/certbot-auto
- name: Add cron job for SSL renewal
  cron:
    name: "Renew SSL Certificate"
    minute: "0"
    hour: "2"
    job: "certbot renew --nginx --quiet"

